#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Open Source Geospatial Programming & Remote Sensing  # The title of the book. Will be placed in the left navbar.
author                      : Michael Mann, Steven Chao, Nina Feldman  # The author of the book
#copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : pygis.png  # A path to the book logo
sphinx:
  extra_extensions: []
#  myst_enable_extensions = ["dollarmath", "amsmath"]

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : auto
  exclude_patterns          : []    # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)

only_build_toc_files: true

 
# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

repository:
  url                       : https://github.com/mmann1123/pyGIS  # The URL to your book's repository
  path_to_book              : "./pygis"  # A path to your book's folder, relative to the repository root.
  branch                    : main  # Which branch of the repository should be used when creating links

sphinx:
  config:
    html_show_copyright: false
  extra_extensions:
    - sphinx_sitemap

html:
  use_edit_page_button:         true
  use_issues_button:            true
  home_page_in_navbar:          true
  use_repository_button:        true
  google_analytics_id       :  'UA-192844775-1'  # A GA id that can be used to track book views.
  extra_footer              :  
  extra_footer: |
        <div>
            <b>Supported by:</b>  <br>
            <a href="https://geography.columbian.gwu.edu/">
         <img alt="GW Geography" src="../_static/global/GWBlue.png"
          width="300">
        </div>
        <div>
        <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.
        </div>
# Will be displayed underneath the footer. width=150" height="70"

#######################################################################################
# Launch button settings

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname:                 book.tex

  